services:
    tg-filestreambot:
      image: ghcr.io/tarocats/tg-filestreambot:main
      restart: unless-stopped
      container_name: tg-filestreambot
      env_file:
        - .env
      ports:
       - 9191:9191