name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Comma-separated target platforms for buildx (eg. linux/amd64,linux/arm64)'
        required: false
        default: 'linux/amd64,linux/arm64'
      push:
        description: 'Whether to push the built image to registry (requires DOCKER_USERNAME/DOCKER_PASSWORD)'
        required: false
        default: 'false'
      tag:
        description: 'Image tag to use when pushing (defaults to commit SHA)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry (if provided)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY || 'docker.io' }}

      - name: Build and push multi-arch image (amd64 + arm64)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD && (github.event_name != 'workflow_dispatch' || github.event.inputs.push == 'true') }}
        run: |
          PLATFORMS="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platforms != '' && github.event.inputs.platforms || github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}"
          TAG="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '' && github.event.inputs.tag || github.sha }}"
          docker buildx build \
            --platform "${PLATFORMS}" \
            --file Dockerfile \
            --tag "${{ secrets.DOCKER_REGISTRY || 'docker.io' }}/fsbarm:${TAG}" \
            --push .

      - name: Build local image (no push)
        if: ${{ !secrets.DOCKER_USERNAME || !secrets.DOCKER_PASSWORD || (github.event_name == 'workflow_dispatch' && github.event.inputs.push != 'true') }}
        run: |
          docker build . --file Dockerfile --tag fsbarm:$(date +%s)
